name: Maven Action Workflow DBL 
on:
  push:
    branches:
      - main
env:
  MY_CONTEXT: "Local variable: File scope to all jobs within the yml file"
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        run: |
          echo "Initialization and Configuration:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  codeql:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: CODEQL Running
        run: |
          echo "CODEQL Code Scan Running: Open 'Push on main' job output"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  build:
    needs: codeql
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: |
          CONFIGS=`cat job.properties`
          echo "$CONFIGS" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
          mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Build output statements
      run: |
        echo "Build with Maven completed successfully..."
        CONFIGS=`cat ${{ github.workspace }}/job.properties`
        echo "$CONFIGS" >> $GITHUB_ENV
        echo "${{ env.param1 }}"
        echo "${{ env.param2 }}"
faux_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Faux Deploy Running
        run: |
          echo "Faux Deploy..."
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
faux_publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Faux Publish to GitHub Packages
      run: |
        echo "Faux publish..."
    - name: Listing
      run: |
        ls -la
  post_action:
    needs: faux_publish
    runs-on: ubuntu-latest
    steps:
      - name: Post Action Running
        run: |
          echo "Post Action..."
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
