name: Maven Action Workflow
on:
  push:
    branches:
      - main
      - develop
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization Example Secrets Use
        env:
          MY_DB_USERNAME: ${{ secrets.MY_DB_USERNAME }}
          MY_DB_PASSWORD: ${{ secrets.MY_DB_PASSWORD }}
        run: |
          echo "Deploy artifact:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  codeql:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: CODEQL Running
        run: |
          echo "CODEQL Code Scan Running: Open 'Push on main' job output"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Build output statements
      run: |
        echo "Build with Maven completed successfully..."
        ls -al target
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: yarn run deploy
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}  
    - name: Publish
      run: mvn -file pom.xml install
    - name: Listing
      run: |
        ls -la target
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: target jar
        path: |
          target

          
