name: Maven Action Workflow
on:
  push:
    branches:
      - main
      - develop
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        env:
          MY_DB_USERNAME: ${{ secrets.MY_DB_USERNAME }}
          MY_DB_PASSWORD: ${{ secrets.MY_DB_PASSWORD }}
        run: |
          echo "Deploy artifact:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  checkmarx:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx Scan
        run: |
          echo "Deploy artifact:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Build output statements
      run: |
        echo "Build with Maven completed successfully..."
        ls -al target 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy artifact:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build output statements
        run: |
          echo "echo dir listing..."
          pwd
          ls -al
          cd ..
          ls -al
      - name: Publish artifact
        run: mvn -file pom.xml deploy

          
